version: '3'
services:
  data_ingestion:
    build:
      context: .
      dockerfile: Dockerfiles/data_ingestion.Dockerfile
    container_name: data_ingestion
    networks:
      - supply_chain_net

  kafka_broker:
    image: bitnami/kafka:latest
    container_name: kafka_broker
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - supply_chain_net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - supply_chain_net

  ml_forecasting:
    build:
      context: .
      dockerfile: Dockerfiles/ml_forecasting.Dockerfile
    container_name: ml_forecasting
    networks:
      - supply_chain_net

  db_dashboard:
    build:
      context: .
      dockerfile: Dockerfiles/db_dashboard.Dockerfile
    container_name: db_dashboard
    volumes:
      - ./scripts:/app/scripts  # Ensure access to dashboard.py
      - ./scripts/templates:/app/templates  # For HTML templates
      - ./scripts/static:/app/static  # For CSS and JS assets
    networks:
      - supply_chain_net
    command: python /app/scripts/dashboard.py
    ports:
      - "5000:5000"
    depends_on:
      - kafka_broker
      - zookeeper
      - data_ingestion
      - ml_forecasting

networks:
  supply_chain_net:
    driver: bridge